# Generated by Django 2.0.4 on 2018-05-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
